articles/urls.py
from django.urls import path,include
from . import views
app_name = 'articles'
urlpatterns = [
    path('', views.index,name='index'),
    path('create/',views.create,name='create'),
    path('detail/<int:article_pk>',views.detail,name='detail'),
    path('update/<int:article_pk>',views.update,name='update'),
    path('delete/<int:article_pk>',views.delete,name='delete'),
    path('comment_create/<int:article_pk>',views.comment_create,name='comment_create'),
    path('comment_delete/<int:article_pk>/<int:comment_pk>',views.comment_delete,name='comment_delete'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
  title = models.CharField(max_length=20)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.title


class Comment(models.Model):
  article = models.ForeignKey(Article,on_delete = models.CASCADE)
  content = models.CharField(max_length=100)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.content

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
  class Meta:
    model = Article
    fields = '__all__'


class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    exclude = ['article']

articles/views.py
from django.shortcuts import render,redirect
from .models import Article,Comment
from .forms import ArticleForm,CommentForm
# Create your views here.

def index(request):
  articles = Article.objects.all()
  length = len(articles)
  last_idx = length-1
  context = {
    'articles' : articles,
    'length' : length,
    'last_idx' : last_idx,
  }
  return render(request,'articles/index.html',context)

def create(request):
  if request.method == 'POST':
    form = ArticleForm(request.POST)
    if form.is_valid():
      article = form.save()
      return redirect('articles:detail', article.pk)
  else:
    form = ArticleForm()
  context = {
    'form' : form,
  }
  return render(request,'articles/create.html',context)


def detail(request,article_pk):
  article = Article.objects.get(pk=article_pk)
  comment_form = CommentForm()
  comments = article.comment_set.all()

  '''
  comments = []
  for comment in Comment.object.all():
    if comment.article_id == article_pk:
      comments.append(comment)
  '''
  context = {
    'article' : article,
    'comment_form' : comment_form,
    'comments' : comments,
  }
  return render(request,'articles/detail.html',context)


def update(request,article_pk):
  article = Article.objects.get(pk=article_pk)
  if request.method == 'POST':
    form = ArticleForm(data=request.POST,instance=article)
    if form.is_valid():
      form.save()
      return redirect('articles:detail', article.pk)
      
  else:
    form = ArticleForm(instance=article)
  context = {
    'form' : form,
    'article' : article,
  }
  return render(request,'articles/update.html',context)


def delete(request,article_pk):
  if request.method == 'POST':
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('articles:index')


def comment_create(request,article_pk):
  article = Article.objects.get(pk=article_pk)
  comment_form = CommentForm(request.POST)
  if comment_form.is_valid():
    comment = comment_form.save(commit=False)
    comment.article = article
    comment.save()
    return redirect('articles:detail',article.pk)
  context = {
    'article':article,
    'comment_form':comment_form,
  }
  return render(request,'articles/detail.html',context)


def comment_delete(request,article_pk,comment_pk):
  comment = Comment.objects.get(pk=comment_pk)
  comment.delete()
  return redirect('articles:detail',article_pk)

articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron text-center">
<form action="{% url 'articles:create' %}" method="POST">{% csrf_token %}
  <div >title: {{form.title}}</div>
  <div class="col-sm-12">content:{{form.content}}</div>
  <hr class="my-4">
  <div class="d-flex justify-content-around">
  <button class="btn btn-primary btn-lg">Create</button>
  </form>
  <button class="btn btn-secondary btn-lg" href="{% url 'articles:index' %}">Back</button>
  </div>
</div>


{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}



<div class="jumbotron text-center">
  <h1 class="display-4">{{article.title}}</h1>
  <p class="lead">{{article.content}}</p>
  <hr class="my-4">
  <div class="d-flex justify-content-around">
    <a class="btn btn-primary btn-lg" href="{% url 'articles:update' article.pk %}">Update</a>
 <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#exampleModal">
  Delete
</button>

  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">delete : {{article.title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{% url 'articles:delete' article.pk %}" method="POST">{% csrf_token %}
  <button class="btn btn-danger" > Delete </button>
  </form>
      </div>
    </div>
  </div>
</div>

{{article.created_at}}
  {% for comment in comments %}
  <p>
    {{comment.content}}
    <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method='POST'>{% csrf_token %}
      <input type="submit" value="Delete">
    </form>
  </p>
  {% endfor %}
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">{% csrf_token %}
{{comment_form}}
<input type="submit" value="Comment">
</form>
<hr>
<a href="{% url 'articles:index' %}">Back</a>
<a href="">Update</a>


{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
<div class="card-deck my-3">
{% for article in articles %}
    <div class="col-sm-6 my-3">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">{{article.title}}</h5>
          <p class="card-text">{{article.content}}</p>
          <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">More Detail</a>
        </div>
      </div>
    </div>
{% endfor %}
</div>

{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'articles:update' article.pk %}" method="POST">{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Update">
</form>

<a href="{% url 'articles:detail' article.pk %}">Back</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'articles:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articles:create' %}">Create</a>
      </li>
      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> {% endcomment %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
  {% block content %}
  {% endblock content %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>